@startuml
left to right direction
' Horizontal lines:
' Vertical lines: -->, <--, <-->, ->, -|{, <->
title Model logiczny

map album {
 id => serial PRIMARY KEY
 author => varchar(64)
 title => varchar(64)
 description => text
 created_at => date
}

map image {
 id => serial PRIMARY KEY
 author => varchar(64)
 title => varchar(64)
 ftype => varchar(32)
 description => text
 created_at => date
}

map primary_comment {
 id => serial PRIMARY KEY
 author => varchar(64)
 title => varchar(64)
 content => text
 created_at => date
}

map secondary_comment {
 id => serial PRIMARY KEY
 author => varchar(64)
 title => varchar(64)
 content => text
 created_at => date
}

map tag {
 id => serial PRIMARY KEY
 title => varchar(64)
 author => varchar(64)
 content => text
 created_at => date
}

album --|{ image
image -o{ primary_comment
primary_comment -o{ secondary_comment
image }o--o{ tag
album }o--o{ tag
@enduml
