@startuml
left to right direction
' Horizontal lines:
' Vertical lines: -->, <--, <-->, ->, -|{, <->
title Model fizyczny

map album {
 id => serial PRIMARY KEY
 author => varchar(64)
 title => varchar(64)
 description => text
 created_at => date
}

map image {
 id => serial PRIMARY KEY
 id_album => bigint unsigned
 author => varchar(64)
 title => varchar(64)
 ftype => varchar(32)
 description => text
 created_at => date
}

map primary_comment {
 id => serial PRIMARY KEY
 id_image => bigint unsigned
 author => varchar(64)
 title => varchar(64)
 content => text
 created_at => date
}

map secondary_comment {
 id => serial PRIMARY KEY
 id_primary => bigint unsigned
 author => varchar(64)
 title => varchar(64)
 content => text
 created_at => date
}

map tag {
 id => serial PRIMARY KEY
 title => varchar(64)
 author => varchar(64)
 content => text
 created_at => date
}

map tag_image {
 id_image => bigint unsigned
 id_tag => bigint unsigned
 PRIMARY KEY(id_image, id_tag)
}

map tag_album {
 id_album => bigint unsigned
 id_tag => bigint unsigned
 PRIMARY KEY(id_album, id_tag)
}

album --|{ image
image -o{ primary_comment
primary_comment -o{ secondary_comment
image --o{ tag_image
tag --o{ tag_image
album --o{ tag_album
tag --o{ tag_album

@enduml
